#pragma once

#include <AYEditor/EditorApp.h>
#include <AYEditor/EditorFreecam.h>
#include <AYEditor/EditorSceneDocument.h>
#include <AYEditor/EditorSelection.h>
#include <AYEditor/EditorSelectionContext.h>
#include <AYEditor/EditorCommandStack.h>
#include <AYEditor/EditorCommandSystem.h>
#include <AYEditor/EditorComponentModule.h>
#include <AYEditor/EditorDocumentManager.h>
#include <AYEditor/EditorDockViewHost.h>
#include <AYEditor/EditorExtension.h>
#include <AYEditor/EditorExtensionRegistry.h>
#include <AYEditor/EditorGameView.h>
#include <AYEditor/EditorPlayRuntime.h>
#include <AYEditor/EditorPlayerController.h>
#include <AYEditor/EditorSession.h>
#include <AYEditor/EditorWorldContext.h>
#include <AYEditor/EditorAssetTilePresenter.h>
#include <AYEditor/EditorDslDocument.h>
#include <AYEditor/EditorDslExtension.h>
#include <AYEditor/EditorUiLayoutDocument.h>
#include <AYEditor/EditorUiLayoutExtension.h>
#include <AYEditor/Editor2DViewportModel.h>
#include <AYEditor/EditorTilemapDocument.h>
#include <AYEditor/ImportDialog.h>
#include <AYEditor/ImportedCharacterMapper.h>
#include <AYEditor/Importer.h>
#include <AYEditor/RegisterDefaultEditorModules.h>
#include <AYEditor/EditorWorkspace.h>
